### ISSUE TITLE
urllib2.HTTPError: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by smtp-25** [ZephrFish/GoogD0rker#12]
Same problem...
Please advice.
thanks

**Comment by 0xNanda** [comment]
Bro, status code 429 and 503 point towards the same thing i.e. rate limiting. There's a certain limit up-to which you can scrape google search result. You can do nothing except purchasing the API.

**Comment by ZephrFish** [comment]
Issue isn't with code, it is to do with rate limiting within Google
